theme: osuny-www-design-system
_merge: deep
params:
  additional_csp: cusdis.com 'unsafe-inline'
  projects:
    index:
      layout: list
      truncate_description: 0
      options:
        summary: false
        categories: false
