theme: osuny-www-design-system
_merge: deep
params:
  additional_csp: cusdis.com 'unsafe-inline'
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  projects:
    index:
      layout: list
      truncate_description: 0
