[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/fonctionnalites/2023-recherche-globale-dans-lextranet/index.html"
to = "/fonctionnalites/2028-recherche-globale-dans-lextranet/"

[[redirects]]
from = "/fonctionnalites/2026-web-to-print/index.html"
to = "/fonctionnalites/2027-web-to-print/"

[[redirects]]
from = "/fichiers/2026/index.html"
to = "/fichiers/2026/devis-001935-noesya-rennes-metropolepdf/"

[[redirects]]
from = "/fonctionnalites/2025-ajout-de-feature-lieu-sur-agenda/index.html"
to = "/fonctionnalites/2025-gestion-des-lieux-des-evenements-et-expositions/"

[[redirects]]
from = "/fonctionnalites/2022-ameliorer-la-gestion-des-mots-cles/index.html"
to = "/fonctionnalites/2028-ameliorer-la-gestion-des-mots-cles/"

[[redirects]]
from = "/fonctionnalites/2022-convertir-le-regime-dinscription-en-taxonomy/index.html"
to = "/fonctionnalites/2028-convertir-le-regime-dinscription-en-taxonomy/"

[[redirects]]
from = "/fonctionnalites/2026-amelioration-des-fils-dariane/index.html"
to = "/fonctionnalites/2027-amelioration-des-fils-dariane/"

[[redirects]]
from = "/fonctionnalites/2022-block-map/index.html"
to = "/fonctionnalites/2028-block-map/"

[[redirects]]
from = "/projets/index.html"
to = "/fonctionnalites/"

